### ISSUE TITLE
What's the state of this repo?

### ISSUE THREAD

**Issue by fghaas** [pcuzner/ceph-iscsi-ansible#4]
I am looking to deploy an RBD-LIO gateway with Ansible, and I'm wondering what the current state of this repo is, as it hasn't seen updates in several months.

- I'm aware of commit https://github.com/ceph/ceph-ansible/commit/d3ceab904d97c0f14aca87865f888add76c89380 that @leseb made to the ceph-ansible repo in apparent preparation for getting LIO gateway functionality upstreamed, but it looks like there hasn't been any additional movement on that front.
- There's also an open issue (https://github.com/ceph/ceph-ansible/issues/1031) that indicates this repo is currently in conflict with upstream ceph-ansible.
- Finally, I wonder what people's thoughts are about other (non-iSCSI) LIO frontends. Given the fact that someone might conceivably want a FC SCSI gateway in front of RBD, and [LIO does support this](http://linux-iscsi.org/wiki/Fibre_Channel), perhaps start referring to the SCSI gateway or target gateway rather than an iSCSI gateway?

I'm perfectly willing to make contributions either here or to upstream ceph-ansible, it would just be good if I could avoid dead ends. So thanks in advance for any insight that you can give.

**Comment by pcuzner** [comment]
hi,
Thanks for reaching out. Basically the ceph-iscsi-* projects that I've been working on are potentially going to be moved in the near to into the main ceph project, which includes this repo  being merged into the main ceph ansible project.

I like the thought of FCP as an option, but TBH the focus I've had is ethernet and I think the growth we see in the industry is in 10/40gb and beyond.

**Comment by fghaas** [comment]
I do understand that merging this into ceph-ansible is the plan, but my question is whether or not that plan is moving forward at all (seeing that the current status has been unchanged for several months now).

**Comment by pcuzner** [comment]
Yes it's the plan - it just a question of finding the time :( I've been talking to Sebastien about it, and we've just been too busy to sync up. My ansible modules haven't really changed in those couple of months - my attention switched to providing a RESTAPI and CLI for management after the deployment is done so admins familiar with targetcli have a familiar interface to manage disks and clients.
